/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex relative flex-wrap gap-5 justify-between w-full text-xl font-medium max-md:max-w-full">
      <h1 className="leading-[66px] text-neutral-50">SwiftSwap</h1>
      <nav className="flex gap-8 self-start mt-4 leading-tight text-right text-white">
        <button className="flex flex-col justify-center items-center px-5 py-3.5 whitespace-nowrap bg-orange-400 min-h-[50px] rounded-[50px]">
          Stake
        </button>
        <button className="flex flex-col justify-center items-center px-5 py-3.5 bg-blue-600 min-h-[50px] rounded-[50px]">
          Connect wallet
        </button>
      </nav>
    </header>
  );
};

export default Header;
