/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroContent: React.FC = () => {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex relative flex-col self-stretch my-auto text-neutral-50 max-md:mt-10 max-md:max-w-full">
        <h2 className="text-6xl font-medium bg-clip-text bg-[linear-gradient(268deg,#FFC947_16.84%,#FC6739_84.26%)] leading-[66px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
          The Most User-Friendly Token Swap App is Here
        </h2>
        <p className="self-start mt-8 text-lg leading-7 opacity-70 max-md:max-w-full">
          Do you find yourself constantly navigating through a labyrinth of
          complicated token exchanges and sluggish trade speeds? Say goodbye to
          the hassle and hello to a better trading experience with swiftswap.
        </p>
      </div>
    </div>
  );
};

export default HeroContent;
