/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SwapForm from "./SwapForm";
import HeroContent from "./HeroContent";

const SwiftSwap: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col bg-white">
      <section className="flex relative flex-col px-20 pt-12 pb-64 w-full min-h-[922px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b0642d164fdac0dd8040b0c43130d871b24578e8ebf5911466f928fcdafdbb0b?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <Header />
        <div className="relative mt-16 mb-0 max-md:mt-10 max-md:mb-2.5 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <HeroContent />
            <SwapForm />
          </div>
        </div>
      </section>
    </main>
  );
};

export default SwiftSwap;
