/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TokenInput from "./TokenInput";

const SwapForm: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex relative flex-col grow max-md:mt-10 max-md:max-w-full">
        <h3 className="self-start text-2xl text-neutral-50">SWAP</h3>
        <form className="flex flex-col px-8 py-12 mt-3.5 ml-2.5 rounded-3xl bg-zinc-900 max-md:px-5 max-md:max-w-full">
          <TokenInput token="Celo" amount="435.32001" />
          <TokenInput token="cUSD" showGasPrice />
          <div className="flex flex-col mt-5 text-white h-[81px] max-md:mr-2.5 max-md:max-w-full">
            <p className="text-base">Estimated Gas fee: 0.20$</p>
            <button
              type="submit"
              className="flex flex-col justify-center items-center px-5 py-3.5 mt-7 w-full text-xl font-medium leading-tight text-right whitespace-nowrap bg-blue-600 min-h-[50px] rounded-[50px] max-md:max-w-full"
            >
              Swap
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default SwapForm;
